# Generated by Django 3.0.11 on 2021-01-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="platform",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="election",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="election",
            name="election_email_domain",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="election",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="position",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
