# Generated by Django 3.0.11 on 2021-02-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0004_election_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="whitelist",
            field=models.TextField(blank=True, default=""),
        ),
    ]
