# Generated by Django 3.0.11 on 2021-03-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0005_election_whitelist"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="election",
            name="submission_release_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="voting_release_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
