# Generated by Django 3.0.11 on 2021-03-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0006_auto_20210305_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="platform",
            field=models.TextField(blank=True, default="", max_length=10000),
        ),
        migrations.AlterField(
            model_name="election",
            name="description",
            field=models.TextField(blank=True, default="", max_length=20000),
        ),
        migrations.AlterField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, default="", max_length=20000),
        ),
    ]
