# Generated by Django 3.0.11 on 2021-03-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0007_auto_20210306_0113"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="vote_type",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("ABSTAIN", "Abstain"),
                    ("NO_CONFIDENCE", "No Confidence"),
                ],
                default="NORMAL",
                max_length=20,
            ),
        ),
    ]
