# Generated by Django 3.2.12 on 2022-02-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0009_auto_20210312_0303"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="limit_to_domain",
            field=models.BooleanField(default=True),
        ),
    ]
